apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec: 
      containers:
        - name: postgres
          image: postgres:10.4
          imagePullPolicy: "IfNotPresent"
          ports:
          - containerPort: 5432
            name: postgres
          env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-password
                key: rootpassword
          volumeMounts:
            - name: postgres-persistant-storage
              mountPath: /var/lib/postgresql
      volumes:
        - name: postgres-persistant-storage
          persistentVolumeClaim:
            claimName: postgres-pv-claim